### ISSUE TITLE
Create the project using Phoenix Framework

### ISSUE THREAD

**Issue by hildersantos** [iureguimaraes/expho-todo#1]
As we will use Phoenix to build this tasks list app, we should first create the initial project in Phoenix.

If you have not installed Phoenix yet on your machine, try to install it using the [official installation guide](https://hexdocs.pm/phoenix/installation.html#erlang-22-or-later).

After that, you should create a new Phoenix project and name it `Expho` (please check the [instructions](https://hexdocs.pm/phoenix/1.6.11/Mix.Tasks.Phx.New.html) on how to develop new Phoenix projects and how the `mix` task treat the project names). By now, the default options should work well - no need to pass additional arguments.

## Tasks
- [ ] Create the Phoenix Framework project named `Expho`
- [ ] Create a branch named, for example, `ft-1/create-project-in-phoenix`
- [ ] Commit it as-is and push it to the newly created branch
- [ ] Open a PR and put me as a reviewer

If you have questions about uploading the project to this repo, you can[ follow this guide](https://medium.com/@bihelca/how-to-upload-project-to-github-581898202adc) starting from step 3.
